config/routes.rb
Rails.application.routes.draw do
  resources :classrooms, path: 'matriculas'

  resources :courses, path: 'cursos'

  resources :students, path: 'estudantes'

  root 'home#index'
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :student
  belongs_to :course

  validates :student_id, :course_id, presence: true
  validates :student_id, uniqueness: { scope: :course_id }

  delegate :name, to: :student, prefix: true, allow_nil: true
  delegate :name, to: :course, prefix: true, allow_nil: true
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :students, through: :classrooms

  validates :name, :description, :status, presence: true
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :courses, through: :classrooms

  validates :name, :register_number, :status, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_classroom, only: [:show, :edit, :update, :destroy]

  # GET /classrooms
  # GET /classrooms.json
  def index
    @classrooms = Classroom.all
  end

  # GET /classrooms/1
  # GET /classrooms/1.json
  def show
  end

  # GET /classrooms/new
  def new
    @classroom = Classroom.new
  end

  # GET /classrooms/1/edit
  def edit
  end

  # POST /classrooms
  # POST /classrooms.json
  def create
    @classroom = Classroom.new(classroom_params)

    respond_to do |format|
      if @classroom.save
        format.html { redirect_to @classroom, notice: I18n.t('helpers.messages.successfully_created') }
        format.json { render action: 'show', status: :created, location: @classroom }
      else
        flash[:error] = I18n.t('errors.messages.errors_found')
        format.html { render action: 'new' }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classrooms/1
  # PATCH/PUT /classrooms/1.json
  def update
    respond_to do |format|
      if @classroom.update(classroom_params)
        format.html { redirect_to @classroom, notice: I18n.t('helpers.messages.successfully_updated') }
        format.json { head :no_content }
      else
        flash[:error] = I18n.t('errors.messages.errors_found')
        format.html { render action: 'edit' }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classrooms/1
  # DELETE /classrooms/1.json
  def destroy
    @classroom.destroy
    respond_to do |format|
      format.html { redirect_to classrooms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classroom
      @classroom = Classroom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def classroom_params
      params.require(:classroom).permit(:student_id, :course_id)
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_cours, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(cours_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: I18n.t('helpers.messages.successfully_created') }
        format.json { render action: 'show', status: :created, location: @course }
      else
        flash[:error] = I18n.t('errors.messages.errors_found')
        format.html { render action: 'new' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(cours_params)
        format.html { redirect_to @course, notice: I18n.t('helpers.messages.successfully_updated') }
        format.json { head :no_content }
      else
        flash[:error] = I18n.t('errors.messages.errors_found')
        format.html { render action: 'edit' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cours
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cours_params
      params.require(:course).permit(:name, :description, :status)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: I18n.t('helpers.messages.successfully_created') }
        format.json { render action: 'show', status: :created, location: @student }
      else
        flash[:error] = I18n.t('errors.messages.errors_found')
        format.html { render action: 'new' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: I18n.t('helpers.messages.successfully_updated') }
        format.json { head :no_content }
      else
        flash[:error] = I18n.t('errors.messages.errors_found')
        format.html { render action: 'edit' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :register_number, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    case flash_type
      when "success"
        "alert-success"
      when "error"
        "alert-danger"
      when "alert"
        "alert-warning"
      when "notice"
        "alert-info"
      else
        flash_type
    end
  end
end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_messages
    flash.collect do |key, msg|
      alert_class = case(key)
      when :notice
        "success"
      when :alert
        "error"
      else
        "info"
      end

      content_tag(:div, msg, :id => key, :class => "alert #{alert_class} center flash-message")
    end.join.html_safe
  end
end

app/helpers/translation_helper.rb
module TranslationHelper
  # Translate model name
  #
  #   <%= tm Post %>
  #   ...
  #   <%= tm Post, 2 %>
  #
  def translate_model_name(model, count = 1)
    model.model_name.human(:count => count)
  end
  alias_method :tm, :translate_model_name

  # Translate model name pluralized
  #
  #   <%= tm Post %>
  #
  def translate_model_name_pluralized(model)
    translate_model_name(model, count = 2)
  end
  alias_method :tmp, :translate_model_name_pluralized

  # Translate a model attribute from config/locales/models-*.yml for more details.
  #
  #   <%= ta Post, :title %>
  #   ...
  #   <%= ta Post, :title, 2 %>
  #
  def translate_model_attribute(model, attribute, count = 1)
    model.human_attribute_name(attribute, :count => count)
  end
  alias_method :ta, :translate_model_attribute
end

app/views/classrooms/_form.html.erb
<div class="row">
	<div class="col-md-4">
		<%= form_for @classroom, validate: true do |c| %>
			<div class="form-group">
				<label for="name">
					<%= Classroom.human_attribute_name(:estudante) %>
				</label>
				<%= c.collection_select(:student_id, Student.all, :id, :name,  { prompt: true }, { :class => 'form-control' } )%>
			</div>
			<div class="form-group">
				<label for="course">
					<%= Classroom.human_attribute_name(:course) %>
				</label>
				<%= c.collection_select(:course_id, Course.all, :id, :name, { prompt: true }, { :class => "form-control", validate: true } ) %>
			</div>
			<%= c.submit %>
		<% end %>
	</div>
	<div class="col-md-4">
	</div>
	<div class="col-md-4">
	</div>
</div>

app/views/classrooms/edit.html.erb
<%- model_class = Classroom -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/classrooms/index.html.erb
<%- model_class = Classroom -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:student) %></th>
      <th><%= model_class.human_attribute_name(:course) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @classrooms.each do |classroom| %>
      <tr>
        <td><%= classroom.student_name %></td>
        <td><%= classroom.course_name %></td>
        <td><%=l classroom.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      classroom_path(classroom), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_classroom_path(classroom), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      classroom_path(classroom),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_classroom_path,
            :class => 'btn btn-primary' %>

app/views/classrooms/new.html.erb
<%- model_class = Classroom -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new_female', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/classrooms/show.html.erb
<%- model_class = Classroom -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:student) %>:</strong></dt>
  <dd><%= @classroom.student_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:course) %>:</strong></dt>
  <dd><%= @classroom.course_name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              classrooms_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_classroom_path(@classroom), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              classroom_path(@classroom),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/courses/_form.html.erb
<div class="row">
	<div class="col-md-4">
		<%= form_for @course, validate: true do |c| %>
			<div class="form-group">

				<label for="name">
					<%= Course.human_attribute_name(:name) %>
				</label>
				<%= c.text_field :name, { placeholder: I18n.t('helpers.masks.course_name'), class: "form-control" } %>
			</div>
			<div class="form-group">

				<label for="description">
					<%= Course.human_attribute_name(:description) %>
				</label>
				<%= c.text_area :description, { placeholder: I18n.t('helpers.masks.description'), class: "form-control" } %>
			</div>
			<div class="form-group">

				<label for="status">
				<%= Course.human_attribute_name(:status) %>
				</label>
				<%= c.text_field :status, { placeholder: I18n.t('helpers.masks.status'), class: "form-control" } %>
			</div>
			<%= c.submit %>
		<% end %>
	</div>
	<div class="col-md-4">
	</div>
	<div class="col-md-4">
	</div>
</div>

app/views/courses/edit.html.erb
<%- model_class = Course -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/courses/index.html.erb
<%- model_class = Course -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.description %></td>
        <td><%= course.status %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")), course_path(course), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_course_path(course), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
            course_path(course),
            :method => :delete,
            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
            :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_course_path,
            :class => 'btn btn-primary' %>

app/views/courses/new.html.erb
<%- model_class = Course -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new_male', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/courses/show.html.erb
<%- model_class = Course -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @course.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @course.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @course.status %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              courses_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_course_path(@course), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              course_path(@course),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/home/index.html.erb
<div class="jumbotron">
    <h2>
        <%= t('helpers.titles.hello') %>
    </h2>
    <p>
        <%= t('helpers.titles.welcome_message') %>
    </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>ProficiencyTest</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <nav class="navbar navbar-default" role="navigation">
            <div class="navbar-header">

              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                 <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
              </button> <a class="navbar-brand" href="<%= root_path %>"><%= t('helpers.links.index')%></a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li>
                  <a href="<%= students_path %>"><%= Student.model_name.human.pluralize.titleize %></a>
                </li>
                <li>
                  <a href="<%= courses_path %>"><%= Course.model_name.human.pluralize.titleize %></a>
                </li>
                <li>
                  <a href="<%= classrooms_path %>"><%= Classroom.model_name.human.pluralize.titleize %></a>
                </li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
            </div>
          </nav>
          <%= render partial: "shared/flash_messages", flash: flash %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/students/_form.html.erb
<div class="row">
	<div class="col-md-4">
		<%= form_for @student do |s| %>
			<div class="form-group">

				<label for="name">
					<%= Student.human_attribute_name(:name) %> *
				</label>
				<%= s.text_field :name, { placeholder: I18n.t('helpers.masks.student_name'), class: "form-control" } %>
			</div>
			<div class="form-group">

				<label for="registerNumber">
					<%= Student.human_attribute_name(:register_number) %> *
				</label>
				<%= s.text_field :register_number, { placeholder: I18n.t('helpers.masks.register'), class: "form-control" } %>
			</div>
			<div class="form-group">

				<label for="status">
				<%= Student.human_attribute_name(:status) %> *
				</label>
				<%= s.text_field :status, { placeholder: I18n.t('helpers.masks.status'), class: "form-control" } %>
			</div>
			<%= s.submit %>
		<% end %>
	</div>
	<div class="col-md-4">
	</div>
</div>

app/views/students/edit.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/students/index.html.erb
<div class="row">
  <div class="col-md-12">
    <%- model_class = Student -%>
    <div class="page-header">
      <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
    </div>
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= model_class.human_attribute_name(:name) %></th>
          <th><%= model_class.human_attribute_name(:register_number) %></th>
          <th><%= model_class.human_attribute_name(:status) %></th>
          <th><%=t '.actions', :default => t("helpers.actions") %></th>
        </tr>
      </thead>
      <tbody>
        <% @students.each do |student| %>
          <tr>
            <td><%= student.name %></td>
            <td><%= student.register_number %></td>
            <td><%= student.status %></td>
            <td>
              <%= link_to t('.show', :default => t("helpers.links.show")),
                student_path(student), :class => 'btn btn-default btn-xs' %>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_student_path(student), :class => 'btn btn-default btn-xs' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          student_path(student),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                          :class => 'btn btn-xs btn-danger' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= link_to t('.new', :default => t("helpers.links.new")),
                new_student_path,
                :class => 'btn btn-primary' %>
</div>

app/views/students/new.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new_male', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/students/show.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @student.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:register_number) %>:</strong></dt>
  <dd><%= @student.register_number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @student.status %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              students_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_student_path(@student), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              student_path(@student),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>